### PR TITLE
Fixed the Overlap

### PR DESCRIPTION
**Pull request by Phil94comp**
I fixed the overlap issue between the footer and the quiz questions and text boxes.

### CODE REVIEW

**Review by MargaretThomas — APPROVED** [review]

**Comment by MargaretThomas** [comment]
Would you like to join us in the DevMingler community? We have a discord server where we chat about these projects and other tech topics.

DevMingler website: https://devmingler.github.io/
DevMingler Discord server: https://discord.gg/wujrntWr5w

**Comment by Phil94comp** [comment]
Thank you for the Discord invitation.

**Comment by DevMingler** [comment]
Hi @Phil94comp, are you ready to merge these changes into main?

**Comment by Phil94comp** [comment]
Yes, the changes are ready to be merged into main.

**Comment by DevMingler** [comment]
Great work!

**Pull request merged**
